export default function Head() {
  return (
    <>
      {/* <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" /> */}
      <title>Drinkzz</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/favicon.png" />
    </>
  );
}
